// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cJ1HbbDdev2TUH5UEsak1h
// Component: Arh0J2djgh
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_moon_demo.module.css"; // plasmic-import: cJ1HbbDdev2TUH5UEsak1h/projectcss
import * as sty from "./PlasmicCaseStudy.module.css"; // plasmic-import: Arh0J2djgh/css

export type PlasmicCaseStudy__VariantMembers = {};

export type PlasmicCaseStudy__VariantsArgs = {};
type VariantPropType = keyof PlasmicCaseStudy__VariantsArgs;
export const PlasmicCaseStudy__VariantProps = new Array<VariantPropType>();

export type PlasmicCaseStudy__ArgsType = {};
type ArgPropType = keyof PlasmicCaseStudy__ArgsType;
export const PlasmicCaseStudy__ArgProps = new Array<ArgPropType>();

export type PlasmicCaseStudy__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultCaseStudyProps {
  className?: string;
}

function PlasmicCaseStudy__RenderFunc(props: {
  variants: PlasmicCaseStudy__VariantsArgs;
  args: PlasmicCaseStudy__ArgsType;
  overrides: PlasmicCaseStudy__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
      </Head>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCaseStudy__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicCaseStudy__VariantsArgs;
  args?: PlasmicCaseStudy__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicCaseStudy__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicCaseStudy__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCaseStudy__ArgProps,
      internalVariantPropNames: PlasmicCaseStudy__VariantProps
    });

    return PlasmicCaseStudy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCaseStudy";
  } else {
    func.displayName = `PlasmicCaseStudy.${nodeName}`;
  }
  return func;
}

export const PlasmicCaseStudy = Object.assign(
  // Top-level PlasmicCaseStudy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCaseStudy
    internalVariantProps: PlasmicCaseStudy__VariantProps,
    internalArgProps: PlasmicCaseStudy__ArgProps
  }
);

export default PlasmicCaseStudy;
/* prettier-ignore-end */
