// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cJ1HbbDdev2TUH5UEsak1h
// Component: Rros5WUQOl
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Box from "../../Box"; // plasmic-import: huz2MWCMkl/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_moon_demo.module.css"; // plasmic-import: cJ1HbbDdev2TUH5UEsak1h/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: Rros5WUQOl/css

import Rectangle60Icon from "./icons/PlasmicIcon__Rectangle60"; // plasmic-import: hn4ytj3xmV/icon
import Vector8Icon from "./icons/PlasmicIcon__Vector8"; // plasmic-import: 6lXZjnN056I/icon
import Vector9Icon from "./icons/PlasmicIcon__Vector9"; // plasmic-import: f0h19OJmHuo/icon
import Vector10Icon from "./icons/PlasmicIcon__Vector10"; // plasmic-import: BZJenjoD97k/icon
import Vector11Icon from "./icons/PlasmicIcon__Vector11"; // plasmic-import: v3vvxFarj8Z/icon
import Vector12Icon from "./icons/PlasmicIcon__Vector12"; // plasmic-import: OU2uWDuvzUE/icon
import Vector13Icon from "./icons/PlasmicIcon__Vector13"; // plasmic-import: OPWFGmTytKN/icon
import Vector14Icon from "./icons/PlasmicIcon__Vector14"; // plasmic-import: oKGzJDDUCeo/icon
import Vector15Icon from "./icons/PlasmicIcon__Vector15"; // plasmic-import: LkZYE7mSYAp/icon
import Vector16Icon from "./icons/PlasmicIcon__Vector16"; // plasmic-import: ejRCOTI-0KU/icon
import Vector17Icon from "./icons/PlasmicIcon__Vector17"; // plasmic-import: 6TOfmFH3Nlm/icon
import Vector18Icon from "./icons/PlasmicIcon__Vector18"; // plasmic-import: ooIVdkKVd2-/icon
import Vector19Icon from "./icons/PlasmicIcon__Vector19"; // plasmic-import: WiK6eUeHPZd/icon
import Vector20Icon from "./icons/PlasmicIcon__Vector20"; // plasmic-import: 92gQQWYnrMd/icon
import Vector21Icon from "./icons/PlasmicIcon__Vector21"; // plasmic-import: dw4G4DntpRh/icon
import Vector22Icon from "./icons/PlasmicIcon__Vector22"; // plasmic-import: HTBUJXHYKYe/icon
import Vector23Icon from "./icons/PlasmicIcon__Vector23"; // plasmic-import: PfwjAwWgr3V/icon
import Vector24Icon from "./icons/PlasmicIcon__Vector24"; // plasmic-import: eCkIawq_YyN/icon
import Vector25Icon from "./icons/PlasmicIcon__Vector25"; // plasmic-import: 0b29cJ07pCB/icon
import Vector26Icon from "./icons/PlasmicIcon__Vector26"; // plasmic-import: 3_9lVH4W-gB/icon
import Vector27Icon from "./icons/PlasmicIcon__Vector27"; // plasmic-import: WfCBuHomEbl/icon
import Vector28Icon from "./icons/PlasmicIcon__Vector28"; // plasmic-import: rNkEj5El8le/icon
import Vector29Icon from "./icons/PlasmicIcon__Vector29"; // plasmic-import: VrY_maCnkUp/icon
import Vector30Icon from "./icons/PlasmicIcon__Vector30"; // plasmic-import: fbQQp-uDD4k/icon
import Vector31Icon from "./icons/PlasmicIcon__Vector31"; // plasmic-import: NqGIlTQbGlG/icon
import Vector32Icon from "./icons/PlasmicIcon__Vector32"; // plasmic-import: vCOCfX9OCje/icon
import Vector33Icon from "./icons/PlasmicIcon__Vector33"; // plasmic-import: 7rIpj32fE-E/icon
import Vector34Icon from "./icons/PlasmicIcon__Vector34"; // plasmic-import: IqMQf1hHw5E/icon
import Vector35Icon from "./icons/PlasmicIcon__Vector35"; // plasmic-import: kZJGH1ECspN/icon
import Vector36Icon from "./icons/PlasmicIcon__Vector36"; // plasmic-import: 4BiNbS3YkDb/icon
import Vector37Icon from "./icons/PlasmicIcon__Vector37"; // plasmic-import: l13iHQ88w0x/icon
import Vector38Icon from "./icons/PlasmicIcon__Vector38"; // plasmic-import: yVxp3KaXpc6/icon
import Vector39Icon from "./icons/PlasmicIcon__Vector39"; // plasmic-import: g0VFoO36suq/icon
import Vector40Icon from "./icons/PlasmicIcon__Vector40"; // plasmic-import: 6hOi27MT9/icon
import Vector41Icon from "./icons/PlasmicIcon__Vector41"; // plasmic-import: DfZ1E9GZgA/icon
import Vector42Icon from "./icons/PlasmicIcon__Vector42"; // plasmic-import: FVG-hjgKZM/icon
import Vector43Icon from "./icons/PlasmicIcon__Vector43"; // plasmic-import: vtjCJjCjom/icon
import Vector44Icon from "./icons/PlasmicIcon__Vector44"; // plasmic-import: NAl12LkYIE/icon
import Vector45Icon from "./icons/PlasmicIcon__Vector45"; // plasmic-import: W2AyXRDogF/icon
import Vector46Icon from "./icons/PlasmicIcon__Vector46"; // plasmic-import: ev7gqonaJaE/icon
import Vector47Icon from "./icons/PlasmicIcon__Vector47"; // plasmic-import: 9a_jAlAFSx9/icon
import Vector48Icon from "./icons/PlasmicIcon__Vector48"; // plasmic-import: WNEsyatAguF/icon
import Vector49Icon from "./icons/PlasmicIcon__Vector49"; // plasmic-import: tmLSPw6dRc2/icon
import Vector50Icon from "./icons/PlasmicIcon__Vector50"; // plasmic-import: S3tmpz9asXL/icon
import Vector51Icon from "./icons/PlasmicIcon__Vector51"; // plasmic-import: fUXJN7NfR_j/icon
import Vector52Icon from "./icons/PlasmicIcon__Vector52"; // plasmic-import: 6JEvgfTFtzK/icon
import Vector53Icon from "./icons/PlasmicIcon__Vector53"; // plasmic-import: C4WlXZU6d8R/icon
import Vector54Icon from "./icons/PlasmicIcon__Vector54"; // plasmic-import: YVR9Tw_D9dl/icon
import Vector55Icon from "./icons/PlasmicIcon__Vector55"; // plasmic-import: 5WPMxMv-EyY/icon
import Vector56Icon from "./icons/PlasmicIcon__Vector56"; // plasmic-import: HYwBOolWJNR/icon
import Vector57Icon from "./icons/PlasmicIcon__Vector57"; // plasmic-import: WUXvrsQufDn/icon
import Vector58Icon from "./icons/PlasmicIcon__Vector58"; // plasmic-import: Z2fTO2GLt6J/icon
import Vector59Icon from "./icons/PlasmicIcon__Vector59"; // plasmic-import: 7h4WI1gzAaC/icon
import Vector60Icon from "./icons/PlasmicIcon__Vector60"; // plasmic-import: AuxTSKbPJsV/icon
import Vector61Icon from "./icons/PlasmicIcon__Vector61"; // plasmic-import: 51c-KPNUYnK/icon
import Vector62Icon from "./icons/PlasmicIcon__Vector62"; // plasmic-import: HRV2NjhKMnZ/icon
import Vector63Icon from "./icons/PlasmicIcon__Vector63"; // plasmic-import: wNSugFACwvt/icon
import Vector64Icon from "./icons/PlasmicIcon__Vector64"; // plasmic-import: yCZOnkk8e9G/icon
import Vector65Icon from "./icons/PlasmicIcon__Vector65"; // plasmic-import: 6R9nuuEAebI/icon
import Vector66Icon from "./icons/PlasmicIcon__Vector66"; // plasmic-import: KRQU5ktyQI7/icon
import Vector67Icon from "./icons/PlasmicIcon__Vector67"; // plasmic-import: JplkiPEYhJB/icon
import Vector68Icon from "./icons/PlasmicIcon__Vector68"; // plasmic-import: RXBovpp86aC/icon
import Rectangle62Icon from "./icons/PlasmicIcon__Rectangle62"; // plasmic-import: kPVPTvQJzby/icon
import UnionIcon from "./icons/PlasmicIcon__Union"; // plasmic-import: 5qe1jsMy9OV/icon
import Vector69Icon from "./icons/PlasmicIcon__Vector69"; // plasmic-import: 2z1QoYNiUhy/icon
import SubtractIcon from "./icons/PlasmicIcon__Subtract"; // plasmic-import: BCLsrBzeZvM/icon
import Vector7Icon from "./icons/PlasmicIcon__Vector7"; // plasmic-import: fX0b9u0xza_/icon
import Fill1Icon from "./icons/PlasmicIcon__Fill1"; // plasmic-import: SHvI_iX6hTI/icon
import Rectangle58Icon from "./icons/PlasmicIcon__Rectangle58"; // plasmic-import: pREUX3QCCmD/icon
import Rectangle1Icon from "./icons/PlasmicIcon__Rectangle1"; // plasmic-import: isKA4maiwY3/icon
import Fill2Icon from "./icons/PlasmicIcon__Fill2"; // plasmic-import: fWWsDPaApkF/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: C5qd5pvu0XR/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: xch7StOAl0E/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: 2MO7iRPjvfq/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: tdL4ef5Dcjp/icon
import Vector5Icon from "./icons/PlasmicIcon__Vector5"; // plasmic-import: HPdJs1Vtsd9/icon
import Vector6Icon from "./icons/PlasmicIcon__Vector6"; // plasmic-import: nKZ6r_sS-_v/icon
import Vector70Icon from "./icons/PlasmicIcon__Vector70"; // plasmic-import: XtynCvPdbkK/icon
import Vector71Icon from "./icons/PlasmicIcon__Vector71"; // plasmic-import: r4w-6gzO4o5/icon
import Vector72Icon from "./icons/PlasmicIcon__Vector72"; // plasmic-import: cpRlXFgtx2P/icon
import Vector73Icon from "./icons/PlasmicIcon__Vector73"; // plasmic-import: wLyZiVdnO-/icon
import Rectangle692Icon from "./icons/PlasmicIcon__Rectangle692"; // plasmic-import: LyuR1i90j7G/icon
import Rectangle682Icon from "./icons/PlasmicIcon__Rectangle682"; // plasmic-import: eIXso2ENb_T/icon

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  home01?: p.Flex<"div">;
  image5?: p.Flex<"div">;
  image4?: p.Flex<"div">;
  rectangle32?: p.Flex<"div">;
  rectangle37?: p.Flex<"div">;
  rectangle38?: p.Flex<"div">;
  rectangle59?: p.Flex<"div">;
  image7?: p.Flex<"div">;
  rectangle382?: p.Flex<"div">;
  rectangle39?: p.Flex<"div">;
  rectangle383?: p.Flex<"div">;
  rectangle41?: p.Flex<"div">;
  rectangle412?: p.Flex<"div">;
  rectangle44?: p.Flex<"div">;
  rectangle45?: p.Flex<"div">;
  group3272?: p.Flex<"div">;
  rectangle432?: p.Flex<"div">;
  social1?: p.Flex<"div">;
  facebook24Outline?: p.Flex<"div">;
  instagram24Outline?: p.Flex<"div">;
  rectangle49?: p.Flex<"div">;
  rectangle50?: p.Flex<"div">;
  image3?: p.Flex<"div">;
  image2?: p.Flex<"div">;
  rectangle33?: p.Flex<"div">;
  group160?: p.Flex<"div">;
  rectangle332?: p.Flex<"div">;
  rectangle333?: p.Flex<"div">;
  rectangle57?: p.Flex<"div">;
  image6?: p.Flex<"div">;
  rectangle61?: p.Flex<"div">;
  rectangle612?: p.Flex<"div">;
  image8?: p.Flex<"div">;
  ブルムンの役割?: p.Flex<"div">;
  frame168?: p.Flex<"div">;
  navigator2?: p.Flex<"div">;
  navigator3?: p.Flex<"div">;
  お知らせ?: p.Flex<"div">;
};

export interface DefaultHomeProps {
  className?: string;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
      </Head>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"home01"}
            data-plasmic-override={overrides.home01}
            className={classNames(defaultcss.all, sty.home01)}
          >
            <div
              data-plasmic-name={"image5"}
              data-plasmic-override={overrides.image5}
              className={classNames(defaultcss.all, sty.image5)}
            />

            <div
              data-plasmic-name={"image4"}
              data-plasmic-override={overrides.image4}
              className={classNames(defaultcss.all, sty.image4)}
            />

            {false ? (
              <div
                data-plasmic-name={"rectangle32"}
                data-plasmic-override={overrides.rectangle32}
                className={classNames(defaultcss.all, sty.rectangle32)}
              />
            ) : null}

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__kWps7
              )}
            >
              {"ブルームーンの役割と5つの強み"}
            </div>

            <div
              data-plasmic-name={"rectangle37"}
              data-plasmic-override={overrides.rectangle37}
              className={classNames(defaultcss.all, sty.rectangle37)}
            />

            <div
              data-plasmic-name={"rectangle38"}
              data-plasmic-override={overrides.rectangle38}
              className={classNames(defaultcss.all, sty.rectangle38)}
            />

            <div
              data-plasmic-name={"rectangle59"}
              data-plasmic-override={overrides.rectangle59}
              className={classNames(defaultcss.all, sty.rectangle59)}
            />

            <Rectangle60Icon
              className={classNames(defaultcss.all, sty.svg__q6Fk5)}
              role={"img"}
            />

            <div
              data-plasmic-name={"image7"}
              data-plasmic-override={overrides.image7}
              className={classNames(defaultcss.all, sty.image7)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___3HW1V
              )}
            >
              {"事例紹介"}
            </div>

            <div
              data-plasmic-name={"rectangle382"}
              data-plasmic-override={overrides.rectangle382}
              className={classNames(defaultcss.all, sty.rectangle382)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___7Podg
              )}
            >
              {"事業概要"}
            </div>

            <div
              data-plasmic-name={"rectangle39"}
              data-plasmic-override={overrides.rectangle39}
              className={classNames(defaultcss.all, sty.rectangle39)}
            />

            <div
              data-plasmic-name={"rectangle383"}
              data-plasmic-override={overrides.rectangle383}
              className={classNames(defaultcss.all, sty.rectangle383)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___61Znq
              )}
            >
              {"ブルームーンの5つの強み"}
            </div>

            <div
              data-plasmic-name={"rectangle41"}
              data-plasmic-override={overrides.rectangle41}
              className={classNames(defaultcss.all, sty.rectangle41)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__eQiq1
              )}
            >
              {
                "ブルームーン・マーケティングには、創業からの10年で創り上げた5つの強みがあります"
              }
            </div>

            <div
              data-plasmic-name={"rectangle412"}
              data-plasmic-override={overrides.rectangle412}
              className={classNames(defaultcss.all, sty.rectangle412)}
            />

            <Vector8Icon
              className={classNames(defaultcss.all, sty.svg__eVp4F)}
              role={"img"}
            />

            <Vector9Icon
              className={classNames(defaultcss.all, sty.svg__tffAu)}
              role={"img"}
            />

            <Vector9Icon
              className={classNames(defaultcss.all, sty.svg__mFyFa)}
              role={"img"}
            />

            <Vector10Icon
              className={classNames(defaultcss.all, sty.svg__nVfm)}
              role={"img"}
            />

            <Vector11Icon
              className={classNames(defaultcss.all, sty.svg__qEAdy)}
              role={"img"}
            />

            <Vector12Icon
              className={classNames(defaultcss.all, sty.svg___1TXi4)}
              role={"img"}
            />

            <Vector13Icon
              className={classNames(defaultcss.all, sty.svg__rLrl0)}
              role={"img"}
            />

            <Vector13Icon
              className={classNames(defaultcss.all, sty.svg__ayBcp)}
              role={"img"}
            />

            <Vector13Icon
              className={classNames(defaultcss.all, sty.svg__mFKtk)}
              role={"img"}
            />

            <Vector14Icon
              className={classNames(defaultcss.all, sty.svg__y6Rpl)}
              role={"img"}
            />

            <Vector14Icon
              className={classNames(defaultcss.all, sty.svg__scwEx)}
              role={"img"}
            />

            <Vector14Icon
              className={classNames(defaultcss.all, sty.svg__fsYF)}
              role={"img"}
            />

            <Vector14Icon
              className={classNames(defaultcss.all, sty.svg__nfg6K)}
              role={"img"}
            />

            <Vector14Icon
              className={classNames(defaultcss.all, sty.svg__efAqu)}
              role={"img"}
            />

            <Vector14Icon
              className={classNames(defaultcss.all, sty.svg___1TMeD)}
              role={"img"}
            />

            <Vector15Icon
              className={classNames(defaultcss.all, sty.svg__eKOwh)}
              role={"img"}
            />

            <Vector16Icon
              className={classNames(defaultcss.all, sty.svg__sg569)}
              role={"img"}
            />

            <Vector17Icon
              className={classNames(defaultcss.all, sty.svg__zouCo)}
              role={"img"}
            />

            <Vector18Icon
              className={classNames(defaultcss.all, sty.svg__rof13)}
              role={"img"}
            />

            <Vector17Icon
              className={classNames(defaultcss.all, sty.svg__vvzn6)}
              role={"img"}
            />

            <Vector19Icon
              className={classNames(defaultcss.all, sty.svg__fdx6N)}
              role={"img"}
            />

            <Vector20Icon
              className={classNames(defaultcss.all, sty.svg__cCcS)}
              role={"img"}
            />

            <Vector20Icon
              className={classNames(defaultcss.all, sty.svg__vzegf)}
              role={"img"}
            />

            <Vector21Icon
              className={classNames(defaultcss.all, sty.svg__i1KTt)}
              role={"img"}
            />

            <Vector22Icon
              className={classNames(defaultcss.all, sty.svg__kKwH6)}
              role={"img"}
            />

            <Vector23Icon
              className={classNames(defaultcss.all, sty.svg__pOwIh)}
              role={"img"}
            />

            <Vector24Icon
              className={classNames(defaultcss.all, sty.svg___4PpJh)}
              role={"img"}
            />

            <Vector24Icon
              className={classNames(defaultcss.all, sty.svg__yEkrt)}
              role={"img"}
            />

            <Vector25Icon
              className={classNames(defaultcss.all, sty.svg__b516P)}
              role={"img"}
            />

            <Vector26Icon
              className={classNames(defaultcss.all, sty.svg__idsuw)}
              role={"img"}
            />

            <Vector27Icon
              className={classNames(defaultcss.all, sty.svg__shKp6)}
              role={"img"}
            />

            <Vector27Icon
              className={classNames(defaultcss.all, sty.svg__amhYn)}
              role={"img"}
            />

            <Vector28Icon
              className={classNames(defaultcss.all, sty.svg__mWNgM)}
              role={"img"}
            />

            <Vector29Icon
              className={classNames(defaultcss.all, sty.svg___5Idix)}
              role={"img"}
            />

            <Vector30Icon
              className={classNames(defaultcss.all, sty.svg___36BH)}
              role={"img"}
            />

            <Vector31Icon
              className={classNames(defaultcss.all, sty.svg__sQasx)}
              role={"img"}
            />

            <Vector32Icon
              className={classNames(defaultcss.all, sty.svg__xp8W5)}
              role={"img"}
            />

            <Vector33Icon
              className={classNames(defaultcss.all, sty.svg__kLgnu)}
              role={"img"}
            />

            <Vector34Icon
              className={classNames(defaultcss.all, sty.svg__kSrWh)}
              role={"img"}
            />

            <Vector35Icon
              className={classNames(defaultcss.all, sty.svg__xapfb)}
              role={"img"}
            />

            <Vector36Icon
              className={classNames(defaultcss.all, sty.svg__ekxuz)}
              role={"img"}
            />

            <Vector37Icon
              className={classNames(defaultcss.all, sty.svg__lv45S)}
              role={"img"}
            />

            <Vector38Icon
              className={classNames(defaultcss.all, sty.svg__mNwX2)}
              role={"img"}
            />

            <Vector39Icon
              className={classNames(defaultcss.all, sty.svg___7QSod)}
              role={"img"}
            />

            <Vector40Icon
              className={classNames(defaultcss.all, sty.svg___7Lxlx)}
              role={"img"}
            />

            <Vector41Icon
              className={classNames(defaultcss.all, sty.svg__zbik6)}
              role={"img"}
            />

            <Vector42Icon
              className={classNames(defaultcss.all, sty.svg__sfAos)}
              role={"img"}
            />

            <Vector43Icon
              className={classNames(defaultcss.all, sty.svg__smQgi)}
              role={"img"}
            />

            <Vector44Icon
              className={classNames(defaultcss.all, sty.svg___9XUi)}
              role={"img"}
            />

            <Vector45Icon
              className={classNames(defaultcss.all, sty.svg__ht8J4)}
              role={"img"}
            />

            <Vector46Icon
              className={classNames(defaultcss.all, sty.svg__mJfHg)}
              role={"img"}
            />

            <Vector47Icon
              className={classNames(defaultcss.all, sty.svg__p636P)}
              role={"img"}
            />

            <Vector48Icon
              className={classNames(defaultcss.all, sty.svg__vRb7O)}
              role={"img"}
            />

            <Vector49Icon
              className={classNames(defaultcss.all, sty.svg__znj20)}
              role={"img"}
            />

            <Vector50Icon
              className={classNames(defaultcss.all, sty.svg__an94)}
              role={"img"}
            />

            <Vector51Icon
              className={classNames(defaultcss.all, sty.svg__n6Whm)}
              role={"img"}
            />

            <Vector52Icon
              className={classNames(defaultcss.all, sty.svg___3Ho8E)}
              role={"img"}
            />

            <Vector53Icon
              className={classNames(defaultcss.all, sty.svg__uzYvj)}
              role={"img"}
            />

            <Vector54Icon
              className={classNames(defaultcss.all, sty.svg__q9NCs)}
              role={"img"}
            />

            <Vector55Icon
              className={classNames(defaultcss.all, sty.svg__g6Xw)}
              role={"img"}
            />

            <Vector56Icon
              className={classNames(defaultcss.all, sty.svg__ukBfi)}
              role={"img"}
            />

            <Vector57Icon
              className={classNames(defaultcss.all, sty.svg__jpGiF)}
              role={"img"}
            />

            <Vector58Icon
              className={classNames(defaultcss.all, sty.svg__mnsSy)}
              role={"img"}
            />

            <Vector59Icon
              className={classNames(defaultcss.all, sty.svg__yKt7)}
              role={"img"}
            />

            <Vector60Icon
              className={classNames(defaultcss.all, sty.svg__nmBt)}
              role={"img"}
            />

            <Vector61Icon
              className={classNames(defaultcss.all, sty.svg___1XlLd)}
              role={"img"}
            />

            <Vector62Icon
              className={classNames(defaultcss.all, sty.svg__ikBix)}
              role={"img"}
            />

            <Vector63Icon
              className={classNames(defaultcss.all, sty.svg___6YXhw)}
              role={"img"}
            />

            <Vector64Icon
              className={classNames(defaultcss.all, sty.svg__r0ZC)}
              role={"img"}
            />

            <Vector65Icon
              className={classNames(defaultcss.all, sty.svg__c2Uhw)}
              role={"img"}
            />

            <Vector66Icon
              className={classNames(defaultcss.all, sty.svg__vLrUk)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___1ZXwP
              )}
            >
              {"さらに見る"}
            </div>

            <Vector67Icon
              className={classNames(defaultcss.all, sty.svg__kh2P4)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__gt3Xa
              )}
            >
              {"2020/12/20"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__pqpAz
              )}
            >
              {"2020/12/20"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___6R8Q
              )}
            >
              {"障害復旧に関するご報告（気象情報の欠落）"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__vOmBc
              )}
            >
              {
                "日本気象協会の「余剰電力予測サービス」が 令和2年度「新エネ大賞」で新エネルギー財団..."
              }
            </div>

            <div
              data-plasmic-name={"rectangle44"}
              data-plasmic-override={overrides.rectangle44}
              className={classNames(defaultcss.all, sty.rectangle44)}
            />

            <div
              data-plasmic-name={"rectangle45"}
              data-plasmic-override={overrides.rectangle45}
              className={classNames(defaultcss.all, sty.rectangle45)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qyaBj
              )}
            >
              {"お知らせ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__ig6P1
              )}
            >
              {"ウェブサイト更新のお知らせ"}
            </div>

            <Box className={classNames("__wab_instance", sty.box__yHneR)} />

            <div
              data-plasmic-name={"group3272"}
              data-plasmic-override={overrides.group3272}
              className={classNames(defaultcss.all, sty.group3272)}
            >
              <div
                data-plasmic-name={"rectangle432"}
                data-plasmic-override={overrides.rectangle432}
                className={classNames(defaultcss.all, sty.rectangle432)}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__urigI
                )}
              >
                {"2020/12/20"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__cvoTn
                )}
              >
                {
                  "[ニュースリリース] GDPR対応のアンケート・システムを感染症およびCX対策に無償提供"
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__uT2F
                )}
              >
                {"続きを読む"}
              </div>
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__mJtN
              )}
            >
              {"続きを読む"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___6D9O
              )}
            >
              {"続きを読む"}
            </div>

            <div
              data-plasmic-name={"social1"}
              data-plasmic-override={overrides.social1}
              className={classNames(defaultcss.all, sty.social1)}
            >
              <div
                data-plasmic-name={"facebook24Outline"}
                data-plasmic-override={overrides.facebook24Outline}
                className={classNames(defaultcss.all, sty.facebook24Outline)}
              />

              <div
                data-plasmic-name={"instagram24Outline"}
                data-plasmic-override={overrides.instagram24Outline}
                className={classNames(defaultcss.all, sty.instagram24Outline)}
              />
            </div>

            <div
              data-plasmic-name={"rectangle49"}
              data-plasmic-override={overrides.rectangle49}
              className={classNames(defaultcss.all, sty.rectangle49)}
            />

            <div
              data-plasmic-name={"rectangle50"}
              data-plasmic-override={overrides.rectangle50}
              className={classNames(defaultcss.all, sty.rectangle50)}
            />

            <Vector68Icon
              className={classNames(defaultcss.all, sty.svg__r1Jgq)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__mwweh
              )}
            >
              {"詳細はこちら"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___1MljM
              )}
            >
              {"詳細はこちら"}
            </div>

            <div
              data-plasmic-name={"image3"}
              data-plasmic-override={overrides.image3}
              className={classNames(defaultcss.all, sty.image3)}
            />

            <div
              data-plasmic-name={"image2"}
              data-plasmic-override={overrides.image2}
              className={classNames(defaultcss.all, sty.image2)}
            />

            <div
              data-plasmic-name={"rectangle33"}
              data-plasmic-override={overrides.rectangle33}
              className={classNames(defaultcss.all, sty.rectangle33)}
            />

            <Rectangle62Icon
              className={classNames(defaultcss.all, sty.svg___12240)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__mjOvX
              )}
            >
              {"お客様との新たな価値創造"}
            </div>

            <UnionIcon
              className={classNames(defaultcss.all, sty.svg__cgv55)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__rn4Yd
              )}
            >
              {
                "東が差善タホカ別病ヌキノメ幻編1殺ソリ木船ぶぽ幕教85守1掲ぶ入舵京そ最小概いフあ。"
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__xWr
              )}
            >
              {"これがスローガンです"}
            </div>

            <Vector69Icon
              className={classNames(defaultcss.all, sty.svg___99MEx)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__avZmQ
              )}
            >
              {"下へスクロール"}
            </div>

            <div
              data-plasmic-name={"group160"}
              data-plasmic-override={overrides.group160}
              className={classNames(defaultcss.all, sty.group160)}
            >
              <div
                data-plasmic-name={"rectangle332"}
                data-plasmic-override={overrides.rectangle332}
                className={classNames(defaultcss.all, sty.rectangle332)}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__pJvPr
                )}
              >
                {"English"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__gwcdi
                )}
              >
                {"日本語"}
              </div>

              <div
                data-plasmic-name={"rectangle333"}
                data-plasmic-override={overrides.rectangle333}
                className={classNames(defaultcss.all, sty.rectangle333)}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box___5WgVb
                )}
              >
                {"お問い合わせ"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__gahGg
                )}
              >
                {"03-6880-9121"}
              </div>

              <SubtractIcon
                className={classNames(defaultcss.all, sty.svg__xV5D)}
                role={"img"}
              />

              <Vector7Icon
                className={classNames(defaultcss.all, sty.svg__ljqOh)}
                role={"img"}
              />

              <Fill1Icon
                className={classNames(defaultcss.all, sty.svg__qdn8T)}
                role={"img"}
              />
            </div>

            <Rectangle58Icon
              className={classNames(defaultcss.all, sty.svg__htr1P)}
              role={"img"}
            />

            <Rectangle1Icon
              className={classNames(defaultcss.all, sty.svg___6Zaa7)}
              role={"img"}
            />

            <Fill2Icon
              className={classNames(defaultcss.all, sty.svg___5Me0)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__zyU0R
              )}
            >
              {"経営理念\r\n会社概要\r\nメンバー\r\n沿革"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__fHeac
              )}
            >
              {"企業情報"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__dows
              )}
            >
              {"経営理念\r\n会社概要\r\nメンバー\r\n沿革"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__htDLb
              )}
            >
              {"企業情報"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__kVjEq
              )}
            >
              {"お問い合わせフォーム"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__h20Ej
              )}
            >
              {"お問い合わせ"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___5Bfuj
              )}
            >
              {"企業向け\nフリーランス向け"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__hBzjB
              )}
            >
              {"事業情報"}
            </div>

            <div
              data-plasmic-name={"rectangle57"}
              data-plasmic-override={overrides.rectangle57}
              className={classNames(defaultcss.all, sty.rectangle57)}
            />

            <VectorIcon
              className={classNames(defaultcss.all, sty.svg__ysfJm)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(defaultcss.all, sty.svg__ja5Ds)}
              role={"img"}
            />

            <Vector3Icon
              className={classNames(defaultcss.all, sty.svg__yaSge)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___4Yv9O
              )}
            >
              {"フォローする"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___6KS3B
              )}
            >
              {"Bluemoon Inc.無断複写・転載を禁じます。"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__lXnbY
              )}
            >
              {
                "〒590-0942　大阪府堺市堺区材木町東3丁1番7号\r\n(072)-232-5039（代）\rFax (072)-228-1255\r\ninfo@bluemoon.co.jp"
              }
            </div>

            <Vector4Icon
              className={classNames(defaultcss.all, sty.svg__dcsbJ)}
              role={"img"}
            />

            <Vector5Icon
              className={classNames(defaultcss.all, sty.svg__eVad)}
              role={"img"}
            />

            <Vector6Icon
              className={classNames(defaultcss.all, sty.svg__jl1Tu)}
              role={"img"}
            />

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__bdjbN)}
              role={"img"}
              src={"/plasmic/moon_demo/images/ellipse482.svg"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__pcCd
              )}
            >
              {"包括的マーケティング支援"}
            </div>

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__z0Zb6)}
              role={"img"}
              src={"/plasmic/moon_demo/images/ellipse492.svg"}
            />

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__qreJu)}
              role={"img"}
              src={"/plasmic/moon_demo/images/ellipse502.svg"}
            />

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__pg8Vp)}
              role={"img"}
              src={"/plasmic/moon_demo/images/ellipse512.svg"}
            />

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__cVcVo)}
              role={"img"}
              src={"/plasmic/moon_demo/images/ellipse522.svg"}
            />

            <Vector70Icon
              className={classNames(defaultcss.all, sty.svg__ma8Iu)}
              role={"img"}
            />

            <Vector71Icon
              className={classNames(defaultcss.all, sty.svg__yaVfg)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___20Gx8
              )}
            >
              {"調査（定量・定性）支援"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___9JrGs
              )}
            >
              {"広報・PR支援"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__hZfe
              )}
            >
              {"仕組みづくり・プロモーション支援"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__r8T7M
              )}
            >
              {"データプラットフォーム構築"}
            </div>

            <Vector72Icon
              className={classNames(defaultcss.all, sty.svg__fithl)}
              role={"img"}
            />

            <div
              data-plasmic-name={"image6"}
              data-plasmic-override={overrides.image6}
              className={classNames(defaultcss.all, sty.image6)}
            />

            <div
              data-plasmic-name={"rectangle61"}
              data-plasmic-override={overrides.rectangle61}
              className={classNames(defaultcss.all, sty.rectangle61)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__bsAym
              )}
            >
              {
                "暮らしに密着した気象情報と指数情報で注目を集めるデジタルサイネージコンテンツ"
              }
            </div>

            <Vector68Icon
              className={classNames(defaultcss.all, sty.svg__wuaaY)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__wAfY
              )}
            >
              {"株式会社アダストリア デジタル化推進部 部長 穴田 浩一さん"}
            </div>

            <div
              data-plasmic-name={"rectangle612"}
              data-plasmic-override={overrides.rectangle612}
              className={classNames(defaultcss.all, sty.rectangle612)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__r4KPm
              )}
            >
              {"暮らしに密着した気象情報と指数情報で注"}
            </div>

            <Vector68Icon
              className={classNames(defaultcss.all, sty.svg__wsqqi)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__d7UTa
              )}
            >
              {"株式会社アダストリア デジタル化推進部 部長 穴田 浩一さん"}
            </div>

            <div
              data-plasmic-name={"image8"}
              data-plasmic-override={overrides.image8}
              className={classNames(defaultcss.all, sty.image8)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__v2Eg
              )}
            >
              {"さらに見る"}
            </div>

            <div
              data-plasmic-name={"ブルムンの役割"}
              data-plasmic-override={overrides.ブルムンの役割}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.ブルムンの役割
              )}
            >
              {"ブルームーンの役割 "}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__kez3Y
              )}
            >
              {
                "ブルームーン・マーケティングは、事業の軸を「データ＆コミュニケーション」としています。 経営に直結し、事業の仕組み・基盤づくりでもあるマーケティング活動領域全般を、「データ＆コミュニケーション」を中心に..."
              }
            </div>

            <Vector73Icon
              className={classNames(defaultcss.all, sty.svg__yOrcj)}
              role={"img"}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame168"}
              data-plasmic-override={overrides.frame168}
              hasGap={true}
              className={classNames(defaultcss.all, sty.frame168)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"navigator2"}
                data-plasmic-override={overrides.navigator2}
                hasGap={true}
                className={classNames(defaultcss.all, sty.navigator2)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__eUj9X
                  )}
                >
                  {"Top"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___166Sq
                  )}
                >
                  {"ブルームーンについて"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__oNkv0
                  )}
                >
                  {"事業概要"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__uYo3W
                  )}
                >
                  {"会社情報"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"navigator3"}
                data-plasmic-override={overrides.navigator3}
                hasGap={true}
                className={classNames(defaultcss.all, sty.navigator3)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__zjUvb
                  )}
                >
                  {"問い合わせ"}
                </div>

                <div
                  data-plasmic-name={"お知らせ"}
                  data-plasmic-override={overrides.お知らせ}
                  className={classNames(defaultcss.all, sty.お知らせ)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__foojX
                    )}
                  >
                    {"お知らせ"}
                  </div>
                </div>
              </p.Stack>
            </p.Stack>

            <Rectangle692Icon
              className={classNames(defaultcss.all, sty.svg__ksWc6)}
              role={"img"}
            />

            <Rectangle682Icon
              className={classNames(defaultcss.all, sty.svg___4Kuro)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "home01",
    "image5",
    "image4",
    "rectangle32",
    "rectangle37",
    "rectangle38",
    "rectangle59",
    "image7",
    "rectangle382",
    "rectangle39",
    "rectangle383",
    "rectangle41",
    "rectangle412",
    "rectangle44",
    "rectangle45",
    "group3272",
    "rectangle432",
    "social1",
    "facebook24Outline",
    "instagram24Outline",
    "rectangle49",
    "rectangle50",
    "image3",
    "image2",
    "rectangle33",
    "group160",
    "rectangle332",
    "rectangle333",
    "rectangle57",
    "image6",
    "rectangle61",
    "rectangle612",
    "image8",
    "ブルムンの役割",
    "frame168",
    "navigator2",
    "navigator3",
    "お知らせ"
  ],
  home01: [
    "home01",
    "image5",
    "image4",
    "rectangle32",
    "rectangle37",
    "rectangle38",
    "rectangle59",
    "image7",
    "rectangle382",
    "rectangle39",
    "rectangle383",
    "rectangle41",
    "rectangle412",
    "rectangle44",
    "rectangle45",
    "group3272",
    "rectangle432",
    "social1",
    "facebook24Outline",
    "instagram24Outline",
    "rectangle49",
    "rectangle50",
    "image3",
    "image2",
    "rectangle33",
    "group160",
    "rectangle332",
    "rectangle333",
    "rectangle57",
    "image6",
    "rectangle61",
    "rectangle612",
    "image8",
    "ブルムンの役割",
    "frame168",
    "navigator2",
    "navigator3",
    "お知らせ"
  ],
  image5: ["image5"],
  image4: ["image4"],
  rectangle32: ["rectangle32"],
  rectangle37: ["rectangle37"],
  rectangle38: ["rectangle38"],
  rectangle59: ["rectangle59"],
  image7: ["image7"],
  rectangle382: ["rectangle382"],
  rectangle39: ["rectangle39"],
  rectangle383: ["rectangle383"],
  rectangle41: ["rectangle41"],
  rectangle412: ["rectangle412"],
  rectangle44: ["rectangle44"],
  rectangle45: ["rectangle45"],
  group3272: ["group3272", "rectangle432"],
  rectangle432: ["rectangle432"],
  social1: ["social1", "facebook24Outline", "instagram24Outline"],
  facebook24Outline: ["facebook24Outline"],
  instagram24Outline: ["instagram24Outline"],
  rectangle49: ["rectangle49"],
  rectangle50: ["rectangle50"],
  image3: ["image3"],
  image2: ["image2"],
  rectangle33: ["rectangle33"],
  group160: ["group160", "rectangle332", "rectangle333"],
  rectangle332: ["rectangle332"],
  rectangle333: ["rectangle333"],
  rectangle57: ["rectangle57"],
  image6: ["image6"],
  rectangle61: ["rectangle61"],
  rectangle612: ["rectangle612"],
  image8: ["image8"],
  ブルムンの役割: ["ブルムンの役割"],
  frame168: ["frame168", "navigator2", "navigator3", "お知らせ"],
  navigator2: ["navigator2"],
  navigator3: ["navigator3", "お知らせ"],
  お知らせ: ["お知らせ"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  home01: "div";
  image5: "div";
  image4: "div";
  rectangle32: "div";
  rectangle37: "div";
  rectangle38: "div";
  rectangle59: "div";
  image7: "div";
  rectangle382: "div";
  rectangle39: "div";
  rectangle383: "div";
  rectangle41: "div";
  rectangle412: "div";
  rectangle44: "div";
  rectangle45: "div";
  group3272: "div";
  rectangle432: "div";
  social1: "div";
  facebook24Outline: "div";
  instagram24Outline: "div";
  rectangle49: "div";
  rectangle50: "div";
  image3: "div";
  image2: "div";
  rectangle33: "div";
  group160: "div";
  rectangle332: "div";
  rectangle333: "div";
  rectangle57: "div";
  image6: "div";
  rectangle61: "div";
  rectangle612: "div";
  image8: "div";
  ブルムンの役割: "div";
  frame168: "div";
  navigator2: "div";
  navigator3: "div";
  お知らせ: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicHome__VariantsArgs;
  args?: PlasmicHome__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicHome__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    home01: makeNodeComponent("home01"),
    image5: makeNodeComponent("image5"),
    image4: makeNodeComponent("image4"),
    rectangle32: makeNodeComponent("rectangle32"),
    rectangle37: makeNodeComponent("rectangle37"),
    rectangle38: makeNodeComponent("rectangle38"),
    rectangle59: makeNodeComponent("rectangle59"),
    image7: makeNodeComponent("image7"),
    rectangle382: makeNodeComponent("rectangle382"),
    rectangle39: makeNodeComponent("rectangle39"),
    rectangle383: makeNodeComponent("rectangle383"),
    rectangle41: makeNodeComponent("rectangle41"),
    rectangle412: makeNodeComponent("rectangle412"),
    rectangle44: makeNodeComponent("rectangle44"),
    rectangle45: makeNodeComponent("rectangle45"),
    group3272: makeNodeComponent("group3272"),
    rectangle432: makeNodeComponent("rectangle432"),
    social1: makeNodeComponent("social1"),
    facebook24Outline: makeNodeComponent("facebook24Outline"),
    instagram24Outline: makeNodeComponent("instagram24Outline"),
    rectangle49: makeNodeComponent("rectangle49"),
    rectangle50: makeNodeComponent("rectangle50"),
    image3: makeNodeComponent("image3"),
    image2: makeNodeComponent("image2"),
    rectangle33: makeNodeComponent("rectangle33"),
    group160: makeNodeComponent("group160"),
    rectangle332: makeNodeComponent("rectangle332"),
    rectangle333: makeNodeComponent("rectangle333"),
    rectangle57: makeNodeComponent("rectangle57"),
    image6: makeNodeComponent("image6"),
    rectangle61: makeNodeComponent("rectangle61"),
    rectangle612: makeNodeComponent("rectangle612"),
    image8: makeNodeComponent("image8"),
    ブルムンの役割: makeNodeComponent("ブルムンの役割"),
    frame168: makeNodeComponent("frame168"),
    navigator2: makeNodeComponent("navigator2"),
    navigator3: makeNodeComponent("navigator3"),
    お知らせ: makeNodeComponent("お知らせ"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
