// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cJ1HbbDdev2TUH5UEsak1h
// Component: huz2MWCMkl
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_moon_demo.module.css"; // plasmic-import: cJ1HbbDdev2TUH5UEsak1h/projectcss
import * as sty from "./PlasmicBox.module.css"; // plasmic-import: huz2MWCMkl/css

export type PlasmicBox__VariantMembers = {};

export type PlasmicBox__VariantsArgs = {};
type VariantPropType = keyof PlasmicBox__VariantsArgs;
export const PlasmicBox__VariantProps = new Array<VariantPropType>();

export type PlasmicBox__ArgsType = {
  boxImg?: React.ReactNode;
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBox__ArgsType;
export const PlasmicBox__ArgProps = new Array<ArgPropType>(
  "boxImg",
  "children",
  "slot",
  "slot2"
);

export type PlasmicBox__OverridesType = {
  root?: p.Flex<"div">;
  rectangle43?: p.Flex<"div">;
};

export interface DefaultBoxProps {
  boxImg?: React.ReactNode;
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  className?: string;
}

function PlasmicBox__RenderFunc(props: {
  variants: PlasmicBox__VariantsArgs;
  args: PlasmicBox__ArgsType;
  overrides: PlasmicBox__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"rectangle43"}
        data-plasmic-override={overrides.rectangle43}
        className={classNames(defaultcss.all, sty.rectangle43)}
      >
        <p.PlasmicSlot defaultContents={null} value={args.boxImg} />
      </div>

      <div className={classNames(defaultcss.all, sty.box__rY8G)}>
        <p.PlasmicSlot
          defaultContents={"2020/12/20"}
          value={args.children}
          className={classNames(sty.slotChildren)}
        />
      </div>

      <div className={classNames(defaultcss.all, sty.box__m9KfX)}>
        <p.PlasmicSlot
          defaultContents={
            "[ニュースリリース] GDPR対応のアンケート・システムを感染症およびCX対策に無償提供"
          }
          value={args.slot}
          className={classNames(sty.slotSlot)}
        />
      </div>

      <div className={classNames(defaultcss.all, sty.box__mrz68)}>
        <p.PlasmicSlot
          defaultContents={"続きを読む"}
          value={args.slot2}
          className={classNames(sty.slotSlot2)}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "rectangle43"],
  rectangle43: ["rectangle43"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  rectangle43: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicBox__VariantsArgs;
  args?: PlasmicBox__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicBox__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicBox__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBox__ArgProps,
      internalVariantPropNames: PlasmicBox__VariantProps
    });

    return PlasmicBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBox";
  } else {
    func.displayName = `PlasmicBox.${nodeName}`;
  }
  return func;
}

export const PlasmicBox = Object.assign(
  // Top-level PlasmicBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    rectangle43: makeNodeComponent("rectangle43"),

    // Metadata about props expected for PlasmicBox
    internalVariantProps: PlasmicBox__VariantProps,
    internalArgProps: PlasmicBox__ArgProps
  }
);

export default PlasmicBox;
/* prettier-ignore-end */
